# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runtime: [linux-x64, win-x64]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependancies
      run: dotnet restore -r ${{ matrix.runtime }} Track-Studio.sln

    - name: Build
      run: dotnet build -c Release --no-restore Track-Studio.sln

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --no-restore Track-Studio

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.runtime }}
        path: Track Studio/bin/Release/net8.0/${{ matrix.runtime }}/publish
